### ISSUE TITLE
unified_money.transaction doesn't account for paying yourself

### ISSUE THREAD

**Issue by luk3yx** [C-C-Minetest-Server/unified_money#1]
I think it's easier to show how this issue works than to try and explain it:

![image](https://github.com/C-C-Minetest-Server/unified_money/assets/3182651/0c337dbc-71e4-43f8-8d7f-b5edb8d9cc9b)

I suggest fixing it by doing `local to_balance = unified_money.get_balance(to)` after deducting money from the first account, that way if the account names are different but still point to the same account (for example `singleplayer` and `SINGLEPLAYER` when the backend is case insensitive) the problem will still be fixed.

Also, I don't think `from_balance == false or to_balance == false` will work, the balance would probably be `nil` instead of `false` when the account doesn't exist.

@Emojigit You don't seem to be watching this repository, I hope you don't mind being mentioned.

**Comment by Emojigit** [comment]
Moving to_balance to the end is a good idea, I will do that. I will also add checks to deny transactions from and to the same account.

BTW, in the current system, all account names are case-sensitive. I can add a registration metadata to let backends indicate whether they are case-sensitive. And with the player account plugin mod installed, all account names will be the exact same (case-sensitive) as ther player name.

**Comment by luk3yx** [comment]
> BTW, in the current system, all account names are case-sensitive. I can add a registration metadata to let backends indicate whether they are case-sensitive. And with the player account plugin mod installed, all account names will be the exact same (case-sensitive) as ther player name.

That would work, although I think everything else works okay with case-insensitive backends at the moment.

**Comment by luk3yx** [comment]
Oh, I've just realised that the backend mod in question ([money3](https://content.minetest.net/packages/luk3yx/money3/)) is sort-of case sensitive (`account_exists`, `create_account`, and `set_balance` return false when the player name doesn't have the correct case, however `get_balance` works with any case), maybe it doesn't need a case insensitive flag.
